version: '3.8'

services:
  investor-agent:
    build: .
    ports:
      - "8006:8006"
    volumes:
      - ./tmp:/app/tmp
    environment:
      # Common settings
      - PYTHONUNBUFFERED=1
      
      # Ollama settings
      - OLLAMA_BASE_URL=http://host.docker.internal:11434/api/generate
      - OLLAMA_MODEL=llama3.2:3b
      
      # Groq settings
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=deepseek-r1-distill-llama-70b
      - MODEL=${MODEL:-"groq"}
      
      # Other API keys
      - SERPER_API_KEY=${SERPER_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
